apiVersion: apps/v1
kind: Deployment
metadata:
  name: adb-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adb-web
  template:
    metadata:
      labels:
        app: adb-web
    spec:
      containers:
        - name: web
          image: adb-devops-app:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: adb-app-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: adb-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adb-db-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: "500m"
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: adb-web
spec:
  selector:
    app: adb-web
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
